"""Skills API — CRUD endpoints for managing research skills."""
import re
import textwrap
from pathlib import Path
from typing import Any

import yaml
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, field_validator

from agent_service.skill_registry import SkillRegistry

# ── Module-level registry (shared with ChatBrowserAgent via server.py) ────────

_SKILLS_DIR = Path(__file__).parent.parent / "skills"

registry = SkillRegistry(skills_dir=_SKILLS_DIR)

router = APIRouter(prefix="/skills", tags=["skills"])

# Base/utility skills — excluded from the UI list
_BASE_SKILLS = {"research-navigation"}


# ── Request / response models ─────────────────────────────────────────────────

class OutputFieldDef(BaseModel):
    name: str
    type: str  # "text" | "number" | "link" | "date"


class SkillBody(BaseModel):
    """Friendly skill creation/update payload from the UI form."""
    name: str
    display_name: str = ""
    when_to_use: str = ""       # maps to description in SKILL.md
    subject_label: str = ""     # description of the 'subject' parameter
    instructions: str = ""
    output_fields: list[OutputFieldDef] = []

    @field_validator("name")
    @classmethod
    def validate_name(cls, v: str) -> str:
        v = v.strip().lower()
        if not re.fullmatch(r"[a-z0-9][a-z0-9\-]*", v):
            raise ValueError(
                "Skill name must be lowercase alphanumeric with hyphens only "
                "(e.g. 'company-research'). No spaces or special characters."
            )
        return v


# ── Helpers ───────────────────────────────────────────────────────────────────

_TYPE_MAP = {"text": "str", "number": "float", "link": "str", "date": "str"}


def _to_class_name(slug: str) -> str:
    """Convert 'my-skill' → 'MySkill'."""
    return "".join(part.capitalize() for part in slug.split("-"))


def _build_skill_md(body: SkillBody, *, active: bool = True) -> str:
    """Generate SKILL.md content from a SkillBody."""
    when_to_use   = body.when_to_use.strip()
    subject_label = body.subject_label.strip()
    display_name  = (body.display_name or "").strip() or _to_class_name(body.name)

    # Build parameters YAML block
    params_lines: list[str] = []
    if subject_label:
        params_lines.append("  subject:")
        params_lines.append("    type: string")
        params_lines.append(f"    description: {subject_label}")
        params_lines.append("    extract_from_request: true")

    params_block = "\n".join(params_lines) if params_lines else "  {}"

    # output_schema reference
    class_name = _to_class_name(body.name)
    output_schema_line = f"output_schema: {class_name}List"

    # Description — preserve multi-line with YAML block scalar
    desc_lines = when_to_use.splitlines() if when_to_use else [""]
    if len(desc_lines) == 1:
        description_yaml = f"description: >\n  {desc_lines[0]}"
    else:
        indented = "\n".join(f"  {line}" for line in desc_lines)
        description_yaml = f"description: >\n{indented}"

    active_str = "true" if active else "false"

    frontmatter = (
        f"---\n"
        f"name: {body.name}\n"
        f"display_name: {display_name}\n"
        f"user_created: true\n"
        f"active: {active_str}\n"
        f"{description_yaml}\n"
        f"parameters:\n"
        f"{params_block}\n"
        f"goal: 'Research {{subject}} as requested.'\n"
        f"{output_schema_line}\n"
        f"---\n"
    )

    return frontmatter + "\n" + body.instructions.strip() + "\n"


def _build_output_schema_py(body: SkillBody) -> str:
    """Generate output_schema.py content from a SkillBody."""
    class_name = _to_class_name(body.name)
    item_class = f"{class_name}Item"
    list_class = f"{class_name}List"

    field_lines: list[str] = []
    for f in body.output_fields:
        py_type = _TYPE_MAP.get(f.type, "str")
        safe_name = re.sub(r"[^a-z0-9_]", "_", f.name.lower().replace(" ", "_"))
        field_lines.append(
            f'    {safe_name}: Optional[{py_type}] = Field(default=None, description="{f.name}")'
        )
    field_lines.append('    source: str = Field(description="Source website")')

    fields_block = "\n".join(field_lines) if field_lines else "    pass"

    return textwrap.dedent(f"""\
        \"\"\"Output schema for the {body.name} skill — auto-generated by Skills Builder.\"\"\"
        from pydantic import BaseModel, Field
        from core.models import SkillOutputModel
        from typing import Optional


        class {item_class}(BaseModel):
        {fields_block}


        class {list_class}(SkillOutputModel):
            items: list[{item_class}]
        """)


def _read_frontmatter_raw(skill_md: Path) -> tuple[dict[str, Any], str]:
    """Parse SKILL.md into (frontmatter dict, body string)."""
    text = skill_md.read_text(encoding="utf-8")
    if text.startswith("---"):
        end = text.index("---", 3)
        fm = yaml.safe_load(text[3:end]) or {}
        body = text[end + 3:].strip()
    else:
        fm = {}
        body = text.strip()
    return fm, body


def _write_frontmatter_raw(skill_md: Path, fm: dict[str, Any], body: str) -> None:
    """Rewrite SKILL.md preserving body, only updating frontmatter."""
    fm_text = yaml.dump(fm, allow_unicode=True, default_flow_style=False, sort_keys=False)
    skill_md.write_text(f"---\n{fm_text}---\n\n{body}\n", encoding="utf-8")


def _set_active(skill_dir: Path, active: bool) -> None:
    """Toggle the active flag in SKILL.md frontmatter."""
    skill_md = skill_dir / "SKILL.md"
    fm, body = _read_frontmatter_raw(skill_md)
    fm["active"] = active
    _write_frontmatter_raw(skill_md, fm, body)


def _skill_to_dict(skill_dir: Path) -> dict[str, Any]:
    """Convert a skill directory into the API response dict."""
    skill_md = skill_dir / "SKILL.md"
    if not skill_md.exists():
        raise FileNotFoundError(f"SKILL.md not found in {skill_dir}")

    fm, body = _read_frontmatter_raw(skill_md)

    # is_builtin = NOT user_created (built-in skills ship with the repo)
    is_builtin = not bool(fm.get("user_created", False))

    # active defaults to True unless explicitly set to False
    active = fm.get("active", True)
    if active is None:
        active = True

    # subject_label — first parameter's description
    raw_params = fm.get("parameters") or {}
    subject_label = ""
    if isinstance(raw_params, dict) and raw_params:
        first_param = next(iter(raw_params.values()), {})
        if isinstance(first_param, dict):
            subject_label = first_param.get("description", "")

    # Parse output_fields from output_schema.py if present
    output_fields: list[dict[str, str]] = []
    schema_path = skill_dir / "output_schema.py"
    if schema_path.exists():
        schema_text = schema_path.read_text(encoding="utf-8")
        _REVERSE_TYPE_MAP = {"float": "number", "str": "text"}
        for line in schema_text.splitlines():
            m = re.match(
                r'\s+(\w+):\s+Optional\[(\w+)\]\s*=\s*Field\(', line
            )
            if m:
                fname, ftype = m.group(1), m.group(2)
                if fname == "source":
                    continue
                output_fields.append({
                    "name": fname,
                    "type": _REVERSE_TYPE_MAP.get(ftype, "text"),
                })

    name = fm.get("name", skill_dir.name)
    description = (fm.get("description") or "").strip()
    display_name = (fm.get("display_name") or "").strip() or name

    return {
        "name": name,
        "display_name": display_name,
        "description": description,
        "when_to_use": description,   # alias — same field, friendly label for UI
        "subject_label": subject_label,
        "instructions": body,
        "output_fields": output_fields,
        "is_builtin": is_builtin,
        "active": bool(active),
        "requires": fm.get("requires") or [],
    }


def _reload_agent() -> None:
    """Reload the shared registry and, if an agent is active, its registry too."""
    registry.load_all()
    # Import here to avoid circular imports at module load time
    try:
        from app import server as _srv  # noqa: PLC0415
        agent = getattr(_srv, "_agent", None)
        if agent is not None:
            agent.reload_skills()
    except Exception:
        pass


# ── Routes ────────────────────────────────────────────────────────────────────

@router.get("")
async def list_skills() -> list[dict[str, Any]]:
    """Return all skills with their metadata (excluding base/utility skills)."""
    result: list[dict[str, Any]] = []
    for skill_dir in sorted(_SKILLS_DIR.iterdir()):
        if not skill_dir.is_dir():
            continue
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.exists():
            continue
        if skill_dir.name in _BASE_SKILLS:
            continue
        try:
            result.append(_skill_to_dict(skill_dir))
        except Exception:
            pass  # skip malformed skills
    return result


@router.get("/{name}")
async def get_skill(name: str) -> dict[str, Any]:
    """Return a single skill by name."""
    skill_dir = _SKILLS_DIR / name
    if not skill_dir.exists() or not (skill_dir / "SKILL.md").exists():
        raise HTTPException(404, f"Skill '{name}' not found.")
    try:
        return _skill_to_dict(skill_dir)
    except Exception as exc:
        raise HTTPException(500, str(exc)) from exc


@router.post("")
async def create_skill(body: SkillBody) -> dict[str, str]:
    """Create a new skill directory with SKILL.md and optionally output_schema.py."""
    skill_dir = _SKILLS_DIR / body.name
    if skill_dir.exists():
        raise HTTPException(409, f"Skill '{body.name}' already exists.")

    skill_dir.mkdir(parents=True)
    (skill_dir / "SKILL.md").write_text(_build_skill_md(body), encoding="utf-8")
    if body.output_fields:
        (skill_dir / "output_schema.py").write_text(
            _build_output_schema_py(body), encoding="utf-8"
        )

    _reload_agent()
    return {"status": "created", "name": body.name}


@router.put("/{name}")
async def update_skill(name: str, body: SkillBody) -> dict[str, str]:
    """Update an existing skill's SKILL.md and output_schema.py."""
    skill_dir = _SKILLS_DIR / name
    if not skill_dir.exists() or not (skill_dir / "SKILL.md").exists():
        raise HTTPException(404, f"Skill '{name}' not found.")

    # Preserve active flag from existing frontmatter
    fm_existing, _ = _read_frontmatter_raw(skill_dir / "SKILL.md")
    active = bool(fm_existing.get("active", True))

    (skill_dir / "SKILL.md").write_text(_build_skill_md(body, active=active), encoding="utf-8")

    if body.output_fields:
        (skill_dir / "output_schema.py").write_text(
            _build_output_schema_py(body), encoding="utf-8"
        )

    _reload_agent()
    return {"status": "updated", "name": name}


@router.delete("/{name}")
async def disable_skill(name: str) -> dict[str, str]:
    """Soft-delete: set active=false in SKILL.md frontmatter."""
    skill_dir = _SKILLS_DIR / name
    if not skill_dir.exists() or not (skill_dir / "SKILL.md").exists():
        raise HTTPException(404, f"Skill '{name}' not found.")

    _set_active(skill_dir, False)
    _reload_agent()
    return {"status": "disabled", "name": name}


@router.post("/{name}/enable")
async def enable_skill(name: str) -> dict[str, str]:
    """Re-enable a previously disabled skill."""
    skill_dir = _SKILLS_DIR / name
    if not skill_dir.exists() or not (skill_dir / "SKILL.md").exists():
        raise HTTPException(404, f"Skill '{name}' not found.")

    _set_active(skill_dir, True)
    _reload_agent()
    return {"status": "enabled", "name": name}
